import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';

class EventDetails extends StatefulWidget {
  final String cityName;
  final String documentId;

  EventDetails(this.cityName, this.documentId);
  @override
  _EventDetailsState createState() => _EventDetailsState();
}

class _EventDetailsState extends State<EventDetails> {
  var firestoreDb = Firestore.instance;
  bool isLiked = false;
  bool isUnLiked = false;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: ListView(
          children: <Widget>[
            Padding(
              padding: EdgeInsets.only(
                top: 40.0,
              ),
            ),
            Align(
              alignment: Alignment.center,
              child: Text(
                widget.cityName,
                style: TextStyle(
                  fontSize: 25.0,
                ),
              ),
            ),
            StreamBuilder<QuerySnapshot>(
              //to get the snapshot of the documents
              stream: firestoreDb
                  .collection("cities")
                  .document(
                      widget.documentId) //automatically generated by firestore
                  .collection('sports')
                  .snapshots(),
              builder: (context, snapshot) {
                if (snapshot.hasData) {
                  print(snapshot.data.documents);

                  return Column(
                      children: snapshot.data.documents
                          .map((doc) => Container(
                                decoration: BoxDecoration(
                                  borderRadius: new BorderRadius.circular(25.0),
                                  border: Border.all(
                                    color: Colors.blue,
                                  ),
                                ),
                                margin: EdgeInsets.only(
                                  top: 20,
                                  left: 10,
                                  right: 10,
                                ),
                                padding: EdgeInsets.only(
                                  top: 10,
                                  left: 20,
                                  right: 10,
                                  bottom: 10,
                                ),
                                child: Column(
                                  children: <Widget>[
                                    Container(
                                      // alignment: Alignment.center,

                                      padding: EdgeInsets.only(
                                        left: 60.0,
                                        bottom: 10.0,
                                      ),
                                      child: Row(
                                        children: <Widget>[
                                          Text(
                                            doc.data['sport_name'],
                                            style: TextStyle(
                                              fontSize: 20,
                                            ),
                                          ),
                                          SizedBox(
                                            width: 10.0,
                                          ),
                                          SizedBox(
                                            width: 20.0,
                                          ),
                                          InkWell(
                                            onTap: () {
                                              int count =
                                                  doc.data['rating_plus'];
                                              var timeStamp = DateFormat(
                                                      "yyyy-MM-dd hh:mm:ss")
                                                  .format(
                                                DateTime.now(),
                                              );

                                              print(
                                                  'rating_plus >>>>>>>>> $count ');
                                              firestoreDb
                                                  .collection('cities')
                                                  .document(widget.documentId)
                                                  .collection('sports')
                                                  .document(doc.documentID)
                                                  .updateData(
                                                {
                                                  'rating_plus': count + 1,
                                                  'updated_at': timeStamp,
                                                },
                                              );
                                            },
                                            child: Image.asset(
                                              'assets/like.png',
                                              height: 40.0,
                                              width: 40.0,
                                            ),
                                          ),
                                          SizedBox(
                                            width: 20.0,
                                          ),
                                          InkWell(
                                            onTap: () {
                                              var timeStamp = DateFormat(
                                                      "yyyy-MM-dd hh:mm:ss")
                                                  .format(DateTime.now());

                                              firestoreDb
                                                  .collection('cities')
                                                  .document(widget.documentId)
                                                  .collection('sports')
                                                  .document(doc.documentID)
                                                  .updateData(
                                                {
                                                  'rating_minus': 1,
                                                  'updated_at': timeStamp,
                                                },
                                              );
                                            },
                                            child: Image.asset(
                                              'assets/unlike.png',
                                              height: 40.0,
                                              width: 40.0,
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                    Text(
                                      'Data is updated at ${doc.data['updated_at']}',
                                    ),
                                  ],
                                ),
                              ))
                          .toList());
                } else {
                  return SizedBox();
                }
              },
            ),
          ],
        ),
      ),
    );
  }
}
